# This list is used for web search in you api 
crimes_list_api = [
    'Amenazas',
    'Robo a negocio',
    'Homicidio doloso',
    'Feminicidio',
    'Secuestro',
    'Trata de personas',
    'Robo a transeúnte',
    'Extorsión',
    'Robo a casa habitación',
    'Violación',
    'Narcomenudeo',
    'Categoria de bajo impacto',
    'Arma de fuego',
    'Robo de accesorios de auto',
    'Robo a cuentahabiente saliendo del cajero con violencia',
    'Robo de vehículo',
    'Robo a pasajero a bordo de microbus',
    'Robo a repartidor',
    'Robo a pasajero a bordo del metro',
    'Lesiones dolosas por disparo de arma de fuego',
    'Hecho no delictivo',
    'Robo a pasajero a bordo de taxi con violencia',
    'Robo a transportista',
    'Robo de motocicleta'
]

lista_delitos= [
        {'valor': 'AMENAZAS', 'nombre': 'Amenazas'},
        {'valor': 'ROBO A NEGOCIO', 'nombre': 'Robo a negocio'},
        {'valor': 'HOMICIDIO DOLOSO', 'nombre': 'Homicidio doloso'},
        {'valor': 'FEMINICIDIO', 'nombre': 'Feminicidio'},
        {'valor': 'SECUESTRO', 'nombre': 'Secuestro'},
        {'valor': 'TRATA DE PERSONAS', 'nombre': 'Trata de personas'},
        {'valor': 'ROBO A TRANSEÚNTE', 'nombre': 'Robo a transeúnte'},
        {'valor': 'EXTORSIÓN', 'nombre': 'Extorsión'},
        {'valor': 'ROBO A CASA HABITACIÓN', 'nombre': 'Robo a casa habitación'},
        {'valor': 'VIOLACIÓN', 'nombre': 'Violación'},
        {'valor': 'NARCOMENUDEO', 'nombre': 'Narcomenudeo'},
        {'valor': 'CATEGORIA DE BAJO IMPACTO', 'nombre': 'Delito de bajo impacto'},
        {'valor': 'ARMA DE FUEGO', 'nombre': 'Lesión con arma de fuego'},
        {'valor': 'ROBO DE ACCESORIOS DE AUTO', 'nombre': 'Robo de accesorios de auto'},
        {'valor': 'ROBO A CUENTAHABIENTE SALIENDO DEL CAJERO CON VIOLENCIA', 'nombre': 'Robo a cuentahabiente'},
        {'valor': 'ROBO DE VEHÍCULO', 'nombre': 'Robo de vehículo'},
        {'valor': 'ROBO A PASAJERO A BORDO DE MICROBUS', 'nombre': 'Robo en microbús'},
        {'valor': 'ROBO A REPARTIDOR', 'nombre': 'Robo a repartidor'},
        {'valor': 'ROBO A PASAJERO A BORDO DEL METRO', 'nombre': 'Robo en metro'},
        {'valor': 'LESIONES DOLOSAS POR DISPARO DE ARMA DE FUEGO', 'nombre': 'Lesiones por arma de fuego'},
        {'valor': 'HECHO NO DELICTIVO', 'nombre': 'Hecho no delictivo'},
        {'valor': 'ROBO A PASAJERO A BORDO DE TAXI CON VIOLENCIA', 'nombre': 'Robo en taxi'},
        {'valor': 'ROBO A TRANSPORTISTA', 'nombre': 'Robo a transportista'},
]

color_delitos = [
    {'valor': 'AMENAZAS', 'nombre': 'Amenazas', 'color': '#8A2BE2'},
    {'valor': 'ROBO A NEGOCIO', 'nombre': 'Robo a negocio', 'color': '#FF69B4'},
    {'valor': 'HOMICIDIO DOLOSO', 'nombre': 'Homicidio doloso', 'color': '#4B0082'},
    {'valor': 'FEMINICIDIO', 'nombre': 'Feminicidio', 'color': '#DC143C'},
    {'valor': 'SECUUESTRO', 'nombre': 'Secuestro', 'color': '#FF1493'},
    {'valor': 'TRATA DE PERSONAS', 'nombre': 'Trata de personas', 'color': '#B22222'},
    {'valor': 'ROBO A TRANSEÚNTE', 'nombre': 'Robo a transeúnte', 'color': '#00FF00'},
    {'valor': 'EXTORSIÓN', 'nombre': 'Extorsión', 'color': '#DAA520'},
    {'valor': 'ROBO A CASA HABITACIÓN', 'nombre': 'Robo a casa habitación', 'color': '#800080'},
    {'valor': 'VIOLACIÓN', 'nombre': 'Violación', 'color': '#8B0000'},
    {'valor': 'NARCOMENUDEO', 'nombre': 'Narcomenudeo', 'color': '#006400'},
    {'valor': 'CATEGORIA DE BAJO IMPACTO', 'nombre': 'Delito de bajo impacto', 'color': '#A0A0A0'},
    {'valor': 'ARMA DE FUEGO', 'nombre': 'Lesión con arma de fuego', 'color': '#00008B'},
    {'valor': 'ROBO DE ACCESORIOS DE AUTO', 'nombre': 'Robo de accesorios de auto', 'color': '#A0522D'},
    {'valor': 'ROBO A CUENTAHABIENTE SALIENDO DEL CAJERO CON VIOLENCIA', 'nombre': 'Robo a cuentahabiente', 'color': '#FF0000'},
    {'valor': 'ROBO DE VEHÍCULO', 'nombre': 'Robo de vehículo', 'color': '#FFA500'},
    {'valor': 'ROBO A PASAJERO A BORDO DE MICROBUS', 'nombre': 'Robo en microbús', 'color': '#FFD700'},
    {'valor': 'ROBO A REPARTIDOR', 'nombre': 'Robo a repartidor', 'color': '#ADFF2F'},
    {'valor': 'ROBO A PASAJERO A BORDO DEL METRO', 'nombre': 'Robo en metro', 'color': '#00FFFF'},
    {'valor': 'LESIONES DOLOSAS POR DISPARO DE ARMA DE FUEGO', 'nombre': 'Lesiones por arma de fuego', 'color': '#00008B'},
    {'valor': 'HECHO NO DELICTIVO', 'nombre': 'Hecho no delictivo', 'color': '#D3D3D3'},
    {'valor': 'ROBO A PASAJERO A BORDO DE TAXI CON VIOLENCIA', 'nombre': 'Robo en taxi', 'color': '#40E0D0'},
    {'valor': 'ROBO A TRANSPORTISTA', 'nombre': 'Robo a transportista', 'color': '#0000FF'},
]